version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alunos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: alunos
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      API_BASE_URL: http://backend:5000/api/v1/aluno
      API_DATABASE_RESET: http://backend:5000/api/v1/database/reset
volumes:
  db_data: